cfg80211: fix linux version check for port_authorized code
a patch from upstream commit b9e2e550b9a2 ("cfg80211: Update Transition
Disable policy during port authorization") added a few more variables
to cfg80211_port_authorized function. This causes our build to fail
with error below:

```
In file included from drivers/net/wireless/bcmdhd/wl_cfg80211.c:53:
./include/net/cfg80211.h:7894:41: note: expected 'const u8 *' {aka 'const unsigned char *'} but argument is of type 'unsigned int'
 7894 |                               const u8* td_bitmap, u8 td_bitmap_len, gfp_t gfp);
      |                               ~~~~~~~~~~^~~~~~~~~
drivers/net/wireless/bcmdhd/wl_cfg80211.c:22160:17: error: too few arguments to function 'cfg80211_port_authorized'
22160 |                 cfg80211_port_authorized(ndev, (const u8 *)curbssid, GFP_KERNEL);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
./include/net/cfg80211.h:7893:6: note: declared here
 7893 | void cfg80211_port_authorized(struct net_device *dev, const u8 *bssid,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~
```

Remove the check since we do not need it anymore. And so that
linux-6.1 will be using the right amount of parameters in
cfg80211_port_authorized() function call.

Change-Id: I94d469296d338a2f00df283f7ac7d16ab579dc35
Signed-off-by: AFIQE ANUAR <afiqe.anuar@atmark-techno.com>
Fixes: f72774101ea5 ("Merge tag 'v6.1.161' into linux-6.1.y-at")
(cherry picked from commit f2f8b405c02dd810815521268f67c7e952854978)
Signed-off-by: Daisuke Mizobuchi <mizo@atmark-techno.com>